---
  - name: Configure Elk VM with Docker
    hosts: Elk
    remote_user: azdmin
    become: true
    tasks:

    - name: Install docker.io (state=present is option)
      apt:
         name: docker.io
         state: present
         update_cache: yes
    
    - name: Use more memory
      sysctl:
        name: vm.max_map_count
        value: '262144'
        state: present
        reload: yes


    - name: Install python3 (state=present is option)
      apt:
         name: python3-pip
         state: present

    - name: Install Python Docker module
      pip:
         name: docker
         state: present

    - name: Increase virtual memory
      command: sysctl -w vm.max_map_count=262144

    - name: download and launch a docker elk container
      docker_container:
         name: elk
         image: sebp/elk:761
         state: started
         restart_policy: always
         published_ports:
          - "5601:5601"
          - "9200:9200"
          - "5044:5044"

    - name: Enable service docker on boot
      systemd:
         name: docker
         enabled: yes