---
  - name: My first playbook
    hosts: webservers
    become: true
    tasks:

    - name: Install docker.io (state=present is option)
      apt:
         name: docker.io
         state: present
         update_cache: yes

    - name: Install python3 (state=present is option)
      apt:
         name: python3-pip
         state: present

    - name: Install Python Docker module
      pip:
         name: docker
         state: present

    - name: download and launch a docker web container
      docker_container:
        name: dvwa
        image: cyberxsecurity/dvwa
        state: started
        restart_policy: always
        published_ports: 80:80


    - name: Make sure docker service is started
      systemd:
        enabled: yes
        name: docker